#!/bin/bash

SENDMAIL=/usr/sbin/sendmail
SENDTO=all@oddlabs.com
ERRORMAIL=./error_mail

until java -Djava.security.manager -Djava.security.policy=router.policy -server -ea -cp router.jar com.oddlabs.routerserver.RouterServer; do echo "Service crashed, sending report";
cat $ERRORMAIL | $SENDMAIL -oi $SENDTO; done
